### ISSUE TITLE
node-red-contrib-azure-iot-edge-module available again

### ISSUE THREAD

**Issue by iotblackbelt** [kpm-at-hfi/node-red-contrib-azure-iot-edge-kpm#3]
The "official" version of the IoT Edge module nodes is available again. And publsihed on npm and node-red. Can you remove yours? So mine is findable in the palette? Tkanks for hosting it for the time being. 🥇 :-)
Thanks in advance!

**Comment by kpm-at-hfi** [comment]
Sure, I think that's fine. Can you tell me anything about why node-red-contrib-azure-iot-edge-module disappeared? Will this be maintained going forward? Are there any changes (improvements, fixes, whatever) in the node-red-contrib-azure-iot-edge-module you're publishing now?

Glad to have someone back on this! :D

**Comment by kpm-at-hfi** [comment]
Leaving myself the link to @iotblackbelt's repo so I don't have to keep re-looking for it. :)

https://github.com/iotblackbelt/noderededgemodule

**Comment by kpm-at-hfi** [comment]
Good morning @iotblackbelt... thoughts on the above?

**Comment by kpm-at-hfi** [comment]
Closing this as old. Happy to depreciate this module or whatever for the good of the community, but it doesn't appear that this is the time.
